### ISSUE TITLE
Invalid value: "eksattachments": must be a standard resource type or fully qualified

### ISSUE THREAD

**Issue by excieve** [isindir/eks-ebs-node-operator#17]
Container resource name validation is still failing after #16.

```
# * spec.containers[0].resources.limits[eksattachments]: Invalid value: "eksattachments": must be a standard resource type or fully qualified
# * spec.containers[0].resources.limits[eksattachments]: Invalid value: "eksattachments": must be a standard resource for containers
# * spec.containers[0].resources.requests[eksattachments]: Invalid value: "eksattachments": must be a standard resource type or fully qualified
# * spec.containers[0].resources.requests[eksattachments]: Invalid value: "eksattachments": must be a standard resource for containers
```

It appears that any extended resource should follow the fully qualified resource name scheme (e.g. `eks.ebsnodeoperator/attachments`):
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#extended-resources

**Comment by isindir** [comment]
@excieve sorry missed this message somehow.

Could you please send me a bit more information about runtime environment:
* how k8s was installed (eksctl, kops, kubespray, other) and which version of the k8s and or installer you are using ?
* do you use any policy management system which may block nonstandard fields ?
* can you please share example pod definition ?
* can you please share events section from pod with limitation added from command `kubectl describe po` ?

Thanks

**Comment by excieve** [comment]
@isindir No worries, instead of using EBS volumes we ended up deploying Longhorn, which is more suitable for our purposes anyway.

To answer your questions:
 - This was tested on EKS 1.14.x deployed using Terraform and Rancher.
 - Just PSPs, but I don't think they block anything like this.

Unfortunately, I don't have examples and events anymore, sorry. I believe the problem was k8s API server not accepting a spec at all because of extended resource name not being an accepted FQDN.

**Comment by lagivan** [comment]
@isindir facing the same issue now. So I'll answer your questions:

- how k8s was installed (eksctl, kops, kubespray, other) and which version of the k8s and or installer you are using ?
Amazon EKS, kubernetes version 1.15, deployed with Terraform
- do you use any policy management system which may block nonstandard fields ?
No
- can you please share example pod definition ?
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
  labels:
    app: tracemaster
  name: tracemaster
  namespace: prod
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: tracemaster
  serviceName: tracemaster
  template:
    metadata:
      labels:
        app: tracemaster
    spec:
      nodeSelector:
        nodetype: tracemaster
      tolerations:
        - key: dedicated
          operator: Equal
          value: tracemaster
      initContainers:
      - name: init-data
        image: X.dkr.ecr.eu-west-1.amazonaws.com/aws-cli:latest
        imagePullPolicy: IfNotPresent
        command:
        - aws
        - s3
        - sync
        - s3://X
        - /aws
        - --delete
        - --no-progress
        volumeMounts:
         - mountPath: /aws
           name: my-data
        resources:
          limits:
            eksattachments: "1"
          requests:
            eksattachments: "1"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: job-user
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: job-user
              key: AWS_SECRET_ACCESS_KEY
      containers:
      - name: tracemaster
        image: X.dkr.ecr.eu-west-1.amazonaws.com/tracemaster:1.1.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /home/tracemaster/data
          name: my-data
        resources:
          limits:
            cpu: "1.5"
            eksattachments: "1"
          requests:
            memory: "12Gi"
            cpu: "1.0"
            eksattachments: "1"
      volumes:
        - name: my-data
          persistentVolumeClaim:
            claimName: my-data-claim
```
 
- can you please share events section from pod with limitation added from command kubectl describe po ?
Events:
```
  Type     Reason        Age                   From                    Message
  ----     ------        ----                  ----                    -------
  Warning  FailedCreate  2m59s (x18 over 13m)  statefulset-controller  create Pod tracemaster-0 in StatefulSet tracemaster failed error: Pod "tracemaster-0" is invalid: [spec.containers[0].resources.limits[eksattachments]: Invalid value: "eksattachments": must be a standard resource type or fully qualified, spec.containers[0].resources.limits[eksattachments]: Invalid value: "eksattachments": must be a standard resource for containers, spec.containers[0].resources.requests[eksattachments]: Invalid value: "eksattachments": must be a standard resource type or fully qualified, spec.containers[0].resources.requests[eksattachments]: Invalid value: "eksattachments": must be a standard resource for containers, spec.initContainers[0].resources.limits[eksattachments]: Invalid value: "eksattachments": must be a standard resource type or fully qualified, spec.initContainers[0].resources.limits[eksattachments]: Invalid value: "eksattachments": must be a standard resource for containers, spec.initContainers[0].resources.requests[eksattachments]: Invalid value: "eksattachments": must be a standard resource type or fully qualified, spec.initContainers[0].resources.requests[eksattachments]: Invalid value: "eksattachments": must be a standard resource for containers]
```
